ALTER TABLE projects
ADD COLUMN IF NOT EXISTS architecture TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE projects
ADD COLUMN IF NOT EXISTS lessons_learned TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE projects
ADD COLUMN IF NOT EXISTS media JSONB NOT NULL DEFAULT '[]'::JSONB;
